name: Maven CI/CD

on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2  

    - name: Build project with Maven
      run: mvn -B package --file pom.xml

    - name: Install google chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb
        google-chrome-stable --version

    - name: Run the application
      run: java -jar target/github-action-maven-tutorial-1.0-SNAPSHOT-jar-with-dependencies.jar

    - run: | 
        ls -R
        cat out.log

    # - run: mkdir staging && cp target/*jar-with-dependencies.jar staging

    - name: Upload the log file 
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: out.log

  # run-job:
  #     runs-on: ubuntu-latest
  #     needs: [build]
  #     steps:
  #     - uses: actions/checkout@v3
  #     - name: Download Artifact
  #       uses: actions/download-artifact@v3
  #       id: download
  #       with:
  #         name: Package
  #         path:  ${{ github.workspace }}
      
  #     # - run: ls -R
  #     # - run: echo ${{steps.download.outputs.download-path}}
  #     # - run: tar -xvzf ${{steps.download.outputs.download-path}}\\Package.zip"
  #     - run: unzip ${{ github.workspace }}/Package.Zip     
  #     # - run: Expand-Archive -Path ${{ github.workspace }}\\Package.Zip 
      
  #     - uses: actions/setup-java@v3
  #       with:
  #         java-version: '17'
  #         distribution: 'temurin'
  
  #     - run: java -jar Package/github-action-maven-tutorial-1.0-SNAPSHOT-jar-with-dependencies.jar
        
    