name: Maven CI/CD

on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2  

    - name: Build project with Maven
      run: mvn -B package --file pom.xml

    # - name: Run the application
    #   run: java -jar target/github-action-maven-tutorial-1.0-SNAPSHOT-jar-with-dependencies.jar
      
    - run: mkdir staging && cp target/*jar-with-dependencies.jar staging
    
    - name: Upload the jar file 
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging

  run-job:
      runs-on: windows-latest
      needs: [build]
      steps:
      - uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: Package
          
      - run: Expand-Archive -Path Package.Zip 
      
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
  
      - run: java -jar Package/github-action-maven-tutorial-1.0-SNAPSHOT-jar-with-dependencies.jar
        
      - run: ls -R