name: Maven CI/CD

on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2  

    - name: Build project with Maven
      run: mvn -B package --file pom.xml

    - name: Run the application
      run: java -jar target/github-action-maven-tutorial-1.0-SNAPSHOT-jar-with-dependencies.jar
      
    - run: mkdir staging && cp target/*.log staging
    
    - name: Upload the report file 
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: staging

  # upload-reports:
  #     runs-on: windows-latest
  #     needs: [build]
  #     steps:
  #       - uses: actions/checkout@v2
  #       - uses: actions/setup-java@v1
  #         with:
  #           java-version: 14
  #       - run: mvn -B package --file pom.xml
  #       - run: java -jar target/github-action-maven-tutorial-1.0-SNAPSHOT-jar-with-dependencies.jar
  #       # - uses: actions/upload-artifact@v2
  #       #   with:
  #       #     name: out.log
  #       #     path: output